<?php

declare(strict_types=1);

namespace webignition\BasilCompilableSource\Line\Statement;

use webignition\BasilCompilableSource\Line\ExpressionInterface;
use webignition\BasilCompilableSource\Line\ObjectPropertyAccessExpression;

class ObjectPropertyAssignmentStatement extends AssignmentStatement
{
    public function __construct(ObjectPropertyAccessExpression $placeholder, ExpressionInterface $expression)
    {
        parent::__construct(
            new ObjectPropertyAccessExpression(
                $placeholder->getObjectPlaceholder(),
                $placeholder->getProperty()
            ),
            $expression
        );
    }

    public function render(): string
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
